WITH SECOND AS(
    SELECT BOARD_ID, RANK() OVER (ORDER BY b.VIEWS DESC) AS ranks, b.VIEWS
    FROM USED_GOODS_BOARD AS b
)
, FIRST AS (
    SELECT s.BOARD_ID
    FROM SECOND AS s
    WHERE ranks = 1
)
SELECT 
    CONCAT('/home/grep/src/',b.BOARD_ID, '/',f.FILE_ID,f.FILE_NAME,f.FILE_EXT) AS FILE_PATH
FROM 
    USED_GOODS_BOARD AS b
    JOIN 
    USED_GOODS_FILE AS f
    ON 
    b.BOARD_ID = f.BOARD_ID
WHERE
    b.BOARD_ID = (SELECT BOARD_ID FROM FIRST)
ORDER BY
    FILE_PATH DESC
